spring.application.name=iat

# ===============================
# DATABASE (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://172.17.0.2/iat-dev
spring.datasource.username=root
spring.datasource.password=peterson
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==================================
# DEBUG
debug=true
# Mostra SQL
spring.jpa.show-sql=true
# Formata o SQL
spring.jpa.properties.hibernate.format_sql=true
# ==============================
# autenticacao
#api.security.token.secret=${JWT_SECRET:12345678}
