spring.application.name=iat

# ===============================
# DATABASE (MariaDB)
# ===============================
spring.datasource.url=jdbc:mysql://iat:7777/iat_dev

spring.datasource.username=root
spring.datasource.password=peterson
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.devtools.restart.enabled=false

# ==================================
# porta do spring 
server.port=7171
#swagger spring doc 
# http://localhost:<server.port>/swagger-ui/index.html 
#MOSTRAR todo o erro da Requição # em PROD mudar para NEVER
server.error.include-stacktrace=never 
# DEBUG
debug=true
# Mostra SQL
spring.jpa.show-sql=true
# Formata o SQL
spring.jpa.properties.hibernate.format_sql=true
# Exibe os parâmetros dos filtros e inserts muito util para debugar
logging.level.org.hibernate.orm.jdbc.bind=trace
# ==============================
# autenticacao
api.security.token.secret=${JWT_SECRET:12345678}


