spring.application.name=iat

# ===============================
# DATABASE (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://172.17.0.2/iat-dev
spring.datasource.username=root
spring.datasource.password=peterson
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==================================
# DEBUG
debug=true
server.error.include-stacktrace=always

# Mostra SQL
spring.jpa.show-sql=true

# Formata o SQL
spring.jpa.properties.hibernate.format_sql=true

# Mostra os parâmetros enviados (?, ?)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.error.include-stacktrace=never

# Logs gerais
logging.level.root=INFO

# Logs HTTP
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

# Logs do Spring Security
logging.level.org.springframework.security=DEBUG

# Logs do Hibernate (se usar JPA)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================
# autenticacao
api.security.token.secret=${JWT_SECRET:12345678}
